# R Foundamentals

**Table of Contents**
- [Syntax and Data Types](#chapter1)
- [Control Flow and Functions](#chapter2)
- [Data Visualization and EDA](#chapter3)

<a id='chapter1'></a>
## Syntax and Data Types

- [I. Chracters](#character)
- [II. Numerics](#numeric)
- [III. Logicals](#logic)
- [IV. Data Type Conversion](#conversion)
- [V. Vectors](#vector)
- [VI. Seq](#seq)
- [VII. Rep](#rep)
- [VIII. Any, All, Which](#any_all_which)
- [IX. `subset()` 按条件切片](#subset)
- [X. 数组与切片](#matrix_cut)
- [XI. 数组运算](#matrix_calc)
- [XII. DataFrame](#df)

<a id='character'></a>
**I. Characters**

In [22]:
class("Hello")

[1] "character"

In [23]:
class("world")

[1] "character"

In [24]:
class('')

[1] "character"

<a id='numeric'></a>
**II. Numerics**

In [19]:
class(1.2)

[1] "numeric"

In [20]:
class(5)

[1] "numeric"

In [21]:
class(-5.5)

[1] "numeric"

<a id='logic'></a>
**III. Logicals**

In [25]:
class(TRUE)

[1] "logical"

In [26]:
class(FALSE)

[1] "logical"

In [27]:
class(True)

ERROR: Error in eval(expr, envir, enclos): object 'True' not found


<a id='conversion'></a>
**IV. Data Type Conversion**

In [29]:
as.logical(0)

[1] FALSE

In [32]:
# 非零数转换成布尔值均为TRUE
as.logical(5)

[1] TRUE

In [33]:
as.logical('hello')

[1] NA

In [37]:
a = "1.2"
class(a)

[1] "character"

In [38]:
b = as.integer(a)
class(b)

[1] "integer"

In [39]:
as.integer(2.2)

[1] 2

<a id='vector'></a>
**V. Vectors**

syntax:

```
vector(mode=, length=)
```

In [40]:
vector('logical', 2)

[1] FALSE FALSE

In [41]:
vector('numeric', 3)

[1] 0 0 0

In [42]:
vector('character', 5)

[1] "" "" "" "" ""

In [45]:
c('blue', 'green', 'brown', 'brown')

[1] "blue"  "green" "brown" "brown"

In [46]:
c(67, 74, 63, 'yes')

[1] "67"  "74"  "63"  "yes"

<a id='seq'></a>
**VI. seq**

In [43]:
seq(1, 10, 2)

[1] 1 3 5 7 9

利用`length.out`参数，等分两个数

In [49]:
# 类似python中的np.linspace()
seq(1, 10, length.out=8)

[1]  1.000000  2.285714  3.571429  4.857143  6.142857  7.428571  8.714286
[8] 10.000000

In [52]:
seq(0, 1, length.out=11)

[1] 0.0 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.0

<a id='rep'></a>
**VII. rep**

In [44]:
c(rep(2, 3), rep(1, 2))

[1] 2 2 2 1 1

In [50]:
vector('numeric', 5)

[1] 0 0 0 0 0

<a id='any_all_which'></a>
**VIII. `any`, `all` and `which`**

In [54]:
# any
heights = c(67, 74, 63, 70)
any(heights>70)

[1] TRUE

In [55]:
# all
heights = c(67, 74, 63, 70)
all(heights>65)

[1] FALSE

In [58]:
# which
heights = c(67, 74, 63, 70)
which(heights>65)

[1] 1 2 4

In [59]:
# 取反操作
heights = c(67, 74, 63, 70)
which(!heights>65)

[1] 3

<a id='subset'></a>
**IX. `subset()` 按条件切片**

In [62]:
# four people with 1st person eye and height in index 1
# 2nd person has eye and height in index 2
# and so on...

eye.colors = c('blue', 'green', 'brown', 'brown')
heights = c(67, 74, 63, 70)
subset(eye.colors, heights > 70)

[1] "green"

<a id='matrix_cut'></a>
**X. 数组与切片**

In [63]:
my.array = array(seq(1,20,1), dim=c(4,5))
my.array

[,1] [,2] [,3] [,4] [,5]
[1,] 1    5     9   13   17  
[2,] 2    6    10   14   18  
[3,] 3    7    11   15   19  
[4,] 4    8    12   16   20

In [64]:
my.array[4, 2] # 4th row, 2nd column

[1] 8

In [65]:
my.array[1,] # first row

[1]  1  5  9 13 17

In [66]:
my.array[,2] # second column

[1] 5 6 7 8

In [67]:
my.array[c(1,3), c(4,5)]

[,1] [,2]
[1,] 13   17  
[2,] 15   19

In [68]:
my.array[1:3, 3:5]

[,1] [,2] [,3]
[1,]  9   13   17  
[2,] 10   14   18  
[3,] 11   15   19

In [69]:
my.array[-1,]

[,1] [,2] [,3] [,4] [,5]
[1,] 2    6    10   14   18  
[2,] 3    7    11   15   19  
[3,] 4    8    12   16   20

In [73]:
w = seq(0, 1, 0.1)
subset(w, w<.5)

[1] 0.0 0.1 0.2 0.3 0.4

In [75]:
# 与subset()等效
w[w<.5]

[1] 0.0 0.1 0.2 0.3 0.4

In [74]:
which(w<.5)

[1] 1 2 3 4 5

In [76]:
# zero out components
w[w<.5]=0
w

[1] 0.0 0.0 0.0 0.0 0.0 0.5 0.6 0.7 0.8 0.9 1.0

<a id='matrix_calc'></a>
**XI. 数组运算**

- [基于元素的算数运算](#array1)
- [转置 `t()`](#array2)
- [内积（点乘）`%*%`](#array3)
- [行拼接和列拼接 `rbind` & `cbind()`](#array4)

<a id='array1'></a>
**基于元素的算数运算**

**Example 1**

In [77]:
my.array = array(seq(1,4,1), dim=c(2,2))
my.array

[,1] [,2]
[1,] 1    3   
[2,] 2    4

In [78]:
my.array + 10

[,1] [,2]
[1,] 11   13  
[2,] 12   14

**Example 2**

In [109]:
y = array(c(1,2,5,6), dim=c(2,2))
y

[,1] [,2]
[1,] 1    5   
[2,] 2    6

In [110]:
2 * y + 1

[,1] [,2]
[1,] 3    11  
[2,] 5    13

In [111]:
y %*% y

[,1] [,2]
[1,] 11   35  
[2,] 14   46

In [114]:
# test
1*1 + 5*2 
1*5 + 5*6
2*6 + 1*2
2*5 + 6*6

[1] 11

[1] 35

[1] 14

[1] 46

<a id='array2'></a>
**转置 `t()`**

In [80]:
my.array1 = array(c(2, -10, 18, 4, 5, -7, -1, 11, 6), dim=c(3,3))
my.array1

[,1] [,2] [,3]
[1,]   2   4   -1  
[2,] -10   5   11  
[3,]  18  -7    6

In [81]:
t(my.array1)

[,1] [,2] [,3]
[1,]  2   -10  18  
[2,]  4     5  -7  
[3,] -1    11   6

<a id='array3'></a>
**内积（点乘）`%*%`**

___NOTICE:___
1. The number of columns in the first matrix must equal the number of columns in the second matrix.


2. The value in the final matrix for any position is equal to the dot product of the row in the first matrix with the column in the second matrix. 

**Example 1**

In [83]:
my.array1 = array(c(1, 3, 2, 4), dim=c(2,2))
my.array2 = array(c(5, 0, 6, 7), dim=c(2,2))
my.array1
my.array2

[,1] [,2]
[1,] 1    2   
[2,] 3    4

[,1] [,2]
[1,] 5    6   
[2,] 0    7

In [84]:
my.array1 %*% my.array2

[,1] [,2]
[1,]  5   20  
[2,] 15   46

**Example 2**

In [115]:
x <- array(seq(1, 20), dim=c(4, 5))
x

[,1] [,2] [,3] [,4] [,5]
[1,] 1    5     9   13   17  
[2,] 2    6    10   14   18  
[3,] 3    7    11   15   19  
[4,] 4    8    12   16   20

In [116]:
x[1, ] %*% x[1, ]

[,1]
[1,] 565

In [117]:
# test
1*1 + 5*5 + 9*9 + 13*13 + 17*17

[1] 565

In [118]:
# 转置
t(x)

[,1] [,2] [,3] [,4]
[1,]  1    2    3    4  
[2,]  5    6    7    8  
[3,]  9   10   11   12  
[4,] 13   14   15   16  
[5,] 17   18   19   20

<a id='array4'></a>
**行拼接和列拼接 `rbind` & `cbind()`**

**Example 1**

In [87]:
x = 1:3
y = 10:12
x
y

[1] 1 2 3

[1] 10 11 12

In [88]:
cbind(x, y)

x y 
[1,] 1 10
[2,] 2 11
[3,] 3 12

In [89]:
rbind(x, y)

[,1] [,2] [,3]
x  1    2    3  
y 10   11   12

**Example 2**

In [92]:
array1 <- array(c(1, -3, 0, 2), dim=c(2,2))
array1

[,1] [,2]
[1,]  1   0   
[2,] -3   2

In [93]:
array1[1, ] # pulls the first row

[1] 1 0

In [94]:
array1[, 1]

[1]  1 -3

In [96]:
cbind(array1[ ,1], array1[1, ])

[,1] [,2]
[1,]  1   1   
[2,] -3   0

In [97]:
rbind(array1[ ,1], array1[1, ])

[,1] [,2]
[1,] 1    -3  
[2,] 1     0

<a id='df'></a>
**XII. DataFrame**

**Commonly Used Commands:**
1. `head(iris, 7)` - returns top 7 rows of the dataframe


2. `tail(iris, 3)` - returns last 3 rows of the dataframe


3. `dim(iris)` - returns the number of rows and columns in the dataframe


4. `summary(iris)` - returns all the summary statistics for every column in the dataframe


5. `iris$Sepal.Length` - returns the Sepal.Length column (we can do this with any column and the `$`)


6. `min(iris$Sepal.Length)` - returns the min value in the `Sepal.Length` column
    
    There are similar functions `mean()`, `max()`, `median()`, `sd()`, etc.


7. `subset(iris, Species=='virginica' & Petal.Length > 5)` - returns rows meeting these criteria


8. `names(iris)` - show column names


9. `colMeans(iris[, 1:4])` - Means of all four numeric columns

In [127]:
head(iris)

Sepal.Length Sepal.Width Petal.Length Petal.Width Species
1 5.1          3.5         1.4          0.2         setosa 
2 4.9          3.0         1.4          0.2         setosa 
3 4.7          3.2         1.3          0.2         setosa 
4 4.6          3.1         1.5          0.2         setosa 
5 5.0          3.6         1.4          0.2         setosa 
6 5.4          3.9         1.7          0.4         setosa

In [128]:
tail(iris)

Sepal.Length Sepal.Width Petal.Length Petal.Width Species  
145 6.7          3.3         5.7          2.5         virginica
146 6.7          3.0         5.2          2.3         virginica
147 6.3          2.5         5.0          1.9         virginica
148 6.5          3.0         5.2          2.0         virginica
149 6.2          3.4         5.4          2.3         virginica
150 5.9          3.0         5.1          1.8         virginica

In [129]:
head(iris, 10)

Sepal.Length Sepal.Width Petal.Length Petal.Width Species
1  5.1          3.5         1.4          0.2         setosa 
2  4.9          3.0         1.4          0.2         setosa 
3  4.7          3.2         1.3          0.2         setosa 
4  4.6          3.1         1.5          0.2         setosa 
5  5.0          3.6         1.4          0.2         setosa 
6  5.4          3.9         1.7          0.4         setosa 
7  4.6          3.4         1.4          0.3         setosa 
8  5.0          3.4         1.5          0.2         setosa 
9  4.4          2.9         1.4          0.2         setosa 
10 4.9          3.1         1.5          0.1         setosa

In [130]:
names(iris)

[1] "Sepal.Length" "Sepal.Width"  "Petal.Length" "Petal.Width"  "Species"

In [131]:
iris$Sepal.Width

[1] 3.5 3.0 3.2 3.1 3.6 3.9 3.4 3.4 2.9 3.1 3.7 3.4 3.0 3.0 4.0 4.4 3.9 3.5
 [19] 3.8 3.8 3.4 3.7 3.6 3.3 3.4 3.0 3.4 3.5 3.4 3.2 3.1 3.4 4.1 4.2 3.1 3.2
 [37] 3.5 3.6 3.0 3.4 3.5 2.3 3.2 3.5 3.8 3.0 3.8 3.2 3.7 3.3 3.2 3.2 3.1 2.3
 [55] 2.8 2.8 3.3 2.4 2.9 2.7 2.0 3.0 2.2 2.9 2.9 3.1 3.0 2.7 2.2 2.5 3.2 2.8
 [73] 2.5 2.8 2.9 3.0 2.8 3.0 2.9 2.6 2.4 2.4 2.7 2.7 3.0 3.4 3.1 2.3 3.0 2.5
 [91] 2.6 3.0 2.6 2.3 2.7 3.0 2.9 2.9 2.5 2.8 3.3 2.7 3.0 2.9 3.0 3.0 2.5 2.9
[109] 2.5 3.6 3.2 2.7 3.0 2.5 2.8 3.2 3.0 3.8 2.6 2.2 3.2 2.8 2.8 2.7 3.3 3.2
[127] 2.8 3.0 2.8 3.0 2.8 3.8 2.8 2.8 2.6 3.0 3.4 3.1 3.0 3.1 3.1 3.1 2.7 3.2
[145] 3.3 3.0 2.5 3.0 3.4 3.0

In [132]:
mean(iris$Sepal.Width)

[1] 3.057333

In [133]:
median(iris$Sepal.Width)

[1] 3

In [134]:
sd(iris$Sepal.Width)

[1] 0.4358663

In [135]:
virginicas = subset(iris, Species=='virginica')

In [136]:
dim(virginicas)

[1] 50  5

In [137]:
dim(iris)

[1] 150   5

In [149]:
subset(iris, Species=='virginica' & Petal.Length > 5)

Sepal.Length Sepal.Width Petal.Length Petal.Width Species  
101 6.3          3.3         6.0          2.5         virginica
102 5.8          2.7         5.1          1.9         virginica
103 7.1          3.0         5.9          2.1         virginica
104 6.3          2.9         5.6          1.8         virginica
105 6.5          3.0         5.8          2.2         virginica
106 7.6          3.0         6.6          2.1         virginica
108 7.3          2.9         6.3          1.8         virginica
109 6.7          2.5         5.8          1.8         virginica
110 7.2          3.6         6.1          2.5         virginica
111 6.5          3.2         5.1          2.0         virginica
112 6.4          2.7         5.3          1.9         virginica
113 6.8          3.0         5.5          2.1         virginica
115 5.8          2.8         5.1          2.4         virginica
116 6.4          3.2         5.3          2.3         virginica
117 6.5          3.0         5.5          1.8         virginica
118 7.7          3.8         6.7          2.2         virginica
119 7.7          2.6         6.9          2.3         virginica
121 6.9          3.2         5.7          2.3         virginica
123 7.7          2.8         6.7          2.0         virginica
125 6.7          3.3         5.7          2.1         virginica
126 7.2          3.2         6.0          1.8         virginica
129 6.4          2.8         5.6          2.1         virginica
130 7.2          3.0         5.8          1.6         virginica
131 7.4          2.8         6.1          1.9         virginica
132 7.9          3.8         6.4          2.0         virginica
133 6.4          2.8         5.6          2.2         virginica
134 6.3          2.8         5.1          1.5         virginica
135 6.1          2.6         5.6          1.4         virginica
136 7.7          3.0         6.1          2.3         virginica
137 6.3          3.4         5.6          2.4         virginica
138 6.4          3.1         5.5          1.8         virginica
140 6.9          3.1         5.4          2.1         virginica
141 6.7          3.1         5.6          2.4         virginica
142 6.9          3.1         5.1          2.3         virginica
143 5.8          2.7         5.1          1.9         virginica
144 6.8          3.2         5.9          2.3         virginica
145 6.7          3.3         5.7          2.5         virginica
146 6.7          3.0         5.2          2.3         virginica
148 6.5          3.0         5.2          2.0         virginica
149 6.2          3.4         5.4          2.3         virginica
150 5.9          3.0         5.1          1.8         virginica

In [139]:
dim(subset(iris, Species=='virginica' & Petal.Length > 5))

[1] 41  5

In [140]:
summary(iris)

  Sepal.Length    Sepal.Width     Petal.Length    Petal.Width   
 Min.   :4.300   Min.   :2.000   Min.   :1.000   Min.   :0.100  
 1st Qu.:5.100   1st Qu.:2.800   1st Qu.:1.600   1st Qu.:0.300  
 Median :5.800   Median :3.000   Median :4.350   Median :1.300  
 Mean   :5.843   Mean   :3.057   Mean   :3.758   Mean   :1.199  
 3rd Qu.:6.400   3rd Qu.:3.300   3rd Qu.:5.100   3rd Qu.:1.800  
 Max.   :7.900   Max.   :4.400   Max.   :6.900   Max.   :2.500  
       Species  
 setosa    :50  
 versicolor:50  
 virginica :50  
                
                
                

In [141]:
iris[1, 3:4]

Petal.Length Petal.Width
1 1.4          0.2

In [150]:
names(iris)

[1] "Sepal.Length" "Sepal.Width"  "Petal.Length" "Petal.Width"  "Species"

In [151]:
class(iris)

[1] "data.frame"

In [152]:
colMeans(iris[, 1:4])

Sepal.Length  Sepal.Width Petal.Length  Petal.Width 
    5.843333     3.057333     3.758000     1.199333

In [153]:
iris[c(1,3,5), c(3,4)]

Petal.Length Petal.Width
1 1.4          0.2        
3 1.3          0.2        
5 1.4          0.2

<a id='chapter2'></a>
## Control Flow and Functions

- [If/Else Statement](#if_else)
- [Loops](#loop)
- [Functions](#function)

<a id='if_else'></a>
### if ... else statement\

**Example 1**

In [181]:
a = 10; b = 10; c = 1
if (a < b) {
    d = 1
} else if (a == b) {
    d = 2
} else {
    d = 3
}

print(d)

[1] 2


**Example 2**

Suppose you are heating the oven before bakery. The temperature of the oven must be set at 425 degrees. If it's below 425 degrees, it will tell you `oven is not hot enough`; if it is above 425 degrees, it will tell you `oven is too hot`; it will tell you `oven is just right` exactly when it is right just 425 degrees. 

In [189]:
oven.temp = 425
is.it.ready.result1 = "oven is just right"
is.it.ready.result2 = "oven is too hot"
is.it.ready.result3 = "oven is not hot enough"

if (oven.temp == 425){
    print(is.it.ready.result1)
} else if (oven.temp > 425) {
    print(is.it.ready.result2)
} else {
    print(is.it.ready.result3)
}

[1] "oven is just right"


**Example 3**

Using the `where.are.you` variable: if this variable is `"here"`, print `"Come on in"`. If the variable is `"on my way"`, print `"Hurry Up!"`. If the variable is `"I got lost"`, print `"Oh no! You're lost?!"`.

In [191]:
where.are.you1 = 'here'
where.are.you2 = 'on my way'
where.are.you3 = 'I got lost'

result1 = "Come on in"
result2 = 'Hurry Up!'
result3 = "Oh no! You're lost?!"

where.are.you = 'here'

if (where.are.you == where.are.you1){
    print(result1)
} else if (where.are.you == where.are.you2) {
    print(result2)
} else {
    print(result3)
}

[1] "Come on in"


**Example 4**

Use modulars to print if a number stored in the variable `y` is divisible by 4.  For example, imagine `y = 12`. Since 12 is divisible by 4, you would print `"y is divisible by 4"`. If instead `y=5`, 5 is not divisible by 4 without a remainder, you would print `"y is not divisible by 4"`.

In [193]:
# print if y is divisible by 4 or not
y = 20  # some number

# write your solution code here:
res1 = 'y is divisible by 4'
res2 = 'y is not divisible by 4'


if (y %% 4 == 0) {
    print(res1)
} else {
    print(res2)
}

[1] "y is divisible by 4"


<a id='loop'></a>
### Loops

<a id='function'></a>
### Functions

<a id='chapter3'></a>
## Data Visualization and EDA