# R Foundamentals

**Table of Contents**
- [Syntax and Data Types](#chapter1)
- [Control Flow and Functions](#chapter2)
- [Data Visualization and EDA](#chapter3)

<a id='chapter1'></a>
## Syntax and Data Types

**I. Characters**

In [22]:
class("Hello")

[1] "character"

In [23]:
class("world")

[1] "character"

In [24]:
class('')

[1] "character"

**II. Numerics**

In [19]:
class(1.2)

[1] "numeric"

In [20]:
class(5)

[1] "numeric"

In [21]:
class(-5.5)

[1] "numeric"

**III. Logicals**

In [25]:
class(TRUE)

[1] "logical"

In [26]:
class(FALSE)

[1] "logical"

In [27]:
class(True)

ERROR: Error in eval(expr, envir, enclos): object 'True' not found


**IV. Data Type Conversion**

In [29]:
as.logical(0)

[1] FALSE

In [32]:
# 非零数转换成布尔值均为TRUE
as.logical(5)

[1] TRUE

In [33]:
as.logical('hello')

[1] NA

In [37]:
a = "1.2"
class(a)

[1] "character"

In [38]:
b = as.integer(a)
class(b)

[1] "integer"

In [39]:
as.integer(2.2)

[1] 2

**V. Vectors**

syntax:

```
vector(mode=, length=)
```

In [40]:
vector('logical', 2)

[1] FALSE FALSE

In [41]:
vector('numeric', 3)

[1] 0 0 0

In [42]:
vector('character', 5)

[1] "" "" "" "" ""

In [45]:
c('blue', 'green', 'brown', 'brown')

[1] "blue"  "green" "brown" "brown"

In [46]:
c(67, 74, 63, 'yes')

[1] "67"  "74"  "63"  "yes"

**VI. seq**

In [43]:
seq(1, 10, 2)

[1] 1 3 5 7 9

利用`length.out`参数，等分两个数

In [49]:
# 类似python中的np.linspace()
seq(1, 10, length.out=8)

[1]  1.000000  2.285714  3.571429  4.857143  6.142857  7.428571  8.714286
[8] 10.000000

In [52]:
seq(0, 1, length.out=11)

[1] 0.0 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.0

**VII. rep**

In [44]:
c(rep(2, 3), rep(1, 2))

[1] 2 2 2 1 1

In [50]:
vector('numeric', 5)

[1] 0 0 0 0 0

**VIII. `any`, `all` and `which`**

In [54]:
# any
heights = c(67, 74, 63, 70)
any(heights>70)

[1] TRUE

In [55]:
# all
heights = c(67, 74, 63, 70)
all(heights>65)

[1] FALSE

In [58]:
# which
heights = c(67, 74, 63, 70)
which(heights>65)

[1] 1 2 4

In [59]:
# 取反操作
heights = c(67, 74, 63, 70)
which(!heights>65)

[1] 3

**IX. `subset()` 按条件切片**

In [62]:
# four people with 1st person eye and height in index 1
# 2nd person has eye and height in index 2
# and so on...

eye.colors = c('blue', 'green', 'brown', 'brown')
heights = c(67, 74, 63, 70)
subset(eye.colors, heights > 70)

[1] "green"

**X. 数组与切片**

In [63]:
my.array = array(seq(1,20,1), dim=c(4,5))
my.array

[,1] [,2] [,3] [,4] [,5]
[1,] 1    5     9   13   17  
[2,] 2    6    10   14   18  
[3,] 3    7    11   15   19  
[4,] 4    8    12   16   20

In [64]:
my.array[4, 2] # 4th row, 2nd column

[1] 8

In [65]:
my.array[1,] # first row

[1]  1  5  9 13 17

In [66]:
my.array[,2] # second column

[1] 5 6 7 8

In [67]:
my.array[c(1,3), c(4,5)]

[,1] [,2]
[1,] 13   17  
[2,] 15   19

In [68]:
my.array[1:3, 3:5]

[,1] [,2] [,3]
[1,]  9   13   17  
[2,] 10   14   18  
[3,] 11   15   19

In [69]:
my.array[-1,]

[,1] [,2] [,3] [,4] [,5]
[1,] 2    6    10   14   18  
[2,] 3    7    11   15   19  
[3,] 4    8    12   16   20

In [73]:
w = seq(0, 1, 0.1)
subset(w, w<.5)

[1] 0.0 0.1 0.2 0.3 0.4

In [75]:
# 与subset()等效
w[w<.5]

[1] 0.0 0.1 0.2 0.3 0.4

In [74]:
which(w<.5)

[1] 1 2 3 4 5

In [76]:
# zero out components
w[w<.5]=0
w

[1] 0.0 0.0 0.0 0.0 0.0 0.5 0.6 0.7 0.8 0.9 1.0

**XI. 数组运算**

- [基于元素的算数运算](#array1)
- [转置 `t()`](#array2)
- [内积（点乘）`%*%`](#array3)
- [行拼接和列拼接 `rbind` & `cbind()`](#array4)

<a id='array1'></a>
**基于元素的算数运算**

**Example 1**

In [77]:
my.array = array(seq(1,4,1), dim=c(2,2))
my.array

[,1] [,2]
[1,] 1    3   
[2,] 2    4

In [78]:
my.array + 10

[,1] [,2]
[1,] 11   13  
[2,] 12   14

**Example 2**

In [109]:
y = array(c(1,2,5,6), dim=c(2,2))
y

[,1] [,2]
[1,] 1    5   
[2,] 2    6

In [110]:
2 * y + 1

[,1] [,2]
[1,] 3    11  
[2,] 5    13

In [111]:
y %*% y

[,1] [,2]
[1,] 11   35  
[2,] 14   46

In [114]:
# test
1*1 + 5*2 
1*5 + 5*6
2*6 + 1*2
2*5 + 6*6

[1] 11

[1] 35

[1] 14

[1] 46

<a id='array2'></a>
**转置 `t()`**

In [80]:
my.array1 = array(c(2, -10, 18, 4, 5, -7, -1, 11, 6), dim=c(3,3))
my.array1

[,1] [,2] [,3]
[1,]   2   4   -1  
[2,] -10   5   11  
[3,]  18  -7    6

In [81]:
t(my.array1)

[,1] [,2] [,3]
[1,]  2   -10  18  
[2,]  4     5  -7  
[3,] -1    11   6

<a id='array3'></a>
**内积（点乘）`%*%`**

___NOTICE:___
1. The number of columns in the first matrix must equal the number of columns in the second matrix.


2. The value in the final matrix for any position is equal to the dot product of the row in the first matrix with the column in the second matrix. 

**Example 1**

In [83]:
my.array1 = array(c(1, 3, 2, 4), dim=c(2,2))
my.array2 = array(c(5, 0, 6, 7), dim=c(2,2))
my.array1
my.array2

[,1] [,2]
[1,] 1    2   
[2,] 3    4

[,1] [,2]
[1,] 5    6   
[2,] 0    7

In [84]:
my.array1 %*% my.array2

[,1] [,2]
[1,]  5   20  
[2,] 15   46

**Example 2**

In [115]:
x <- array(seq(1, 20), dim=c(4, 5))
x

[,1] [,2] [,3] [,4] [,5]
[1,] 1    5     9   13   17  
[2,] 2    6    10   14   18  
[3,] 3    7    11   15   19  
[4,] 4    8    12   16   20

In [116]:
x[1, ] %*% x[1, ]

[,1]
[1,] 565

In [117]:
# test
1*1 + 5*5 + 9*9 + 13*13 + 17*17

[1] 565

In [118]:
# 转置
t(x)

[,1] [,2] [,3] [,4]
[1,]  1    2    3    4  
[2,]  5    6    7    8  
[3,]  9   10   11   12  
[4,] 13   14   15   16  
[5,] 17   18   19   20

<a id='array4'></a>
**行拼接和列拼接 `rbind` & `cbind()`**

**Example 1**

In [87]:
x = 1:3
y = 10:12
x
y

[1] 1 2 3

[1] 10 11 12

In [88]:
cbind(x, y)

x y 
[1,] 1 10
[2,] 2 11
[3,] 3 12

In [89]:
rbind(x, y)

[,1] [,2] [,3]
x  1    2    3  
y 10   11   12

**Example 2**

In [92]:
array1 <- array(c(1, -3, 0, 2), dim=c(2,2))
array1

[,1] [,2]
[1,]  1   0   
[2,] -3   2

In [93]:
array1[1, ] # pulls the first row

[1] 1 0

In [94]:
array1[, 1]

[1]  1 -3

In [96]:
cbind(array1[ ,1], array1[1, ])

[,1] [,2]
[1,]  1   1   
[2,] -3   0

In [97]:
rbind(array1[ ,1], array1[1, ])

[,1] [,2]
[1,] 1    -3  
[2,] 1     0

<a id='chapter2'></a>
## Control Flow and Functions

<a id='chapter3'></a>
## Data Visualization and EDA